# Generated by Django 5.0.7 on 2024-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='experiencia',
            field=models.IntegerField(),
        ),
    ]
