# Generated by Django 5.0.7 on 2024-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_trabajador_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
