# Generated by Django 5.0.7 on 2024-10-04 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_alter_trabajador_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='sexo',
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.IntegerField(default=18)),
                ('lugar_accidente', models.TextField(blank=True, null=True)),
                ('fecha_suceso', models.CharField(max_length=16, null=True)),
                ('lesion', models.TextField(blank=True, null=True)),
                ('descripcion_hechos', models.TextField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='apiapp.trabajador')),
            ],
        ),
    ]
