# Generated by Django 5.0.7 on 2024-10-07 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_remove_trabajador_sexo_expediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media/')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='apiapp.expediente')),
            ],
        ),
    ]
