# Generated by Django 5.0.7 on 2024-10-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_alter_expediente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='id',
            field=models.CharField(max_length=37, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
