# Generated by Django 5.0.7 on 2024-10-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_alter_imagenes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
