# Generated by Django 5.0.7 on 2024-10-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0015_puestotrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestotrabajo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
