# Generated by Django 5.0.7 on 2024-10-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0019_alter_trabajador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='valoracion_hechos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
