# Generated by Django 5.0.7 on 2024-10-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0020_expediente_valoracion_hechos'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='formas_accidente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
