# Generated by Django 5.0.7 on 2024-10-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0021_expediente_formas_accidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='analisis_causas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
