# Generated by Django 5.0.7 on 2024-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0022_expediente_analisis_causas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausasProducenAccidente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
        ),
    ]
