# Generated by Django 5.0.7 on 2024-10-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0025_expediente_aplicar_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='itinere',
            field=models.BooleanField(default=False),
        ),
    ]
