# Generated by Django 5.0.7 on 2024-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0026_expediente_itinere'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='tipo_suceso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
