# Generated by Django 5.0.7 on 2024-11-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0029_alter_creador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='creador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_investigacion',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
