# Generated by Django 5.0.7 on 2024-11-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0030_expediente_creador_expediente_fecha_investigacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='otros',
            field=models.BooleanField(default=False),
        ),
    ]
