# Generated by Django 5.0.7 on 2024-11-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0031_expediente_otros'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='empresa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
