# Generated by Django 5.0.7 on 2024-11-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0032_expediente_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteCuerpo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
        ),
    ]
