# Generated by Django 5.0.7 on 2024-11-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0035_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaProducirse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
        ),
    ]
