# Generated by Django 5.0.7 on 2024-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0036_formaproducirse'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='agente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='forma_producirse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='parte_cuerpo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo_lesion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
